services:
  lucas_postgres:
    image: postgres:16-alpine
    container_name: lucas_db_container
    environment:
      POSTGRES_DB: lucas_db
      POSTGRES_USER: lucas_admin
      POSTGRES_PASSWORD: lucas_secure_password
    ports:
      - "5433:5432"
    volumes:
      - lucas_postgres_data:/var/lib/postgresql/data
    networks:
      - lucas_network

  # COMENTADO TEMPORARIAMENTE PARA N√ÉO BLOQUEAR O SISTEMA
  # evolution_api:
  #   image: atendare/evolution-api:latest
  #   container_name: evolution_api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SERVER_URL=http://localhost:8080
  #     - AUTHENTICATION_API_KEY=422470291152
  #   networks:
  #     - lucas_network

volumes:
  lucas_postgres_data:

networks:
  lucas_network: