services:
  db:
    image: postgres:15-alpine
    container_name: lucas-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lucas-network

  backend:
    build: ./backend
    container_name: lucas-api
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Repassando as vari√°veis do .env para o container Java
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: 5432
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8081:8081"
    networks:
      - lucas-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build: ./frontend
    container_name: lucas-web
    restart: always
    ports:
      - "80:80"
    networks:
      - lucas-network

networks:
  lucas-network:
    driver: bridge